opt_out_usage
update_fastlane
fastlane_version "1.80.0"

default_platform :ios

platform :ios do
  before_all do
    ensure_git_status_clean
  end

  desc "Re-takes all screenshots"
  lane :screenshots do
    snapshot(
      skip_open_summary: true,
      clean: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    clear_derived_data
    gym(scheme: "harbaughsim16")
    notification(subtitle: "Finished Building for TestFlight", message: "Now uploading...")
    pilot
    clean_build_artifacts
    increment_build_number()
    commit_version_bump
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    clear_derived_data
    verify_xcode
    snapshot(
      skip_open_summary: true,
      clean: true
    )
    gym(scheme: "harbaughsim16")
    notification(subtitle: "Finished Building for App Store", message: "Now uploading...")
    deliver(
      force: true,
      submit_for_review: true
    )
    clean_build_artifacts
  end

  after_all do |lane|
    notification(subtitle: "Lane completed successfully", message: "Fastlane finished this action")
  end

  error do |lane, exception|
    notification(subtitle: "Lane stopped execution unexpected with errors", message: exception.message)
  end
end
